name: rustdoc
on:
  push:
   branches:
   - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    if: github.repository == 'kaist-cp/kecc-public'
    runs-on: [self-hosted, ubuntu-22.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rustup
      run: if ! command -v rustup &>/dev/null; then (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y); fi

    - name: Install Rust toolchain
      run: source "$HOME/.cargo/env"; rustup update --no-self-update stable

    - name: Build Documentation
      run: source "$HOME/.cargo/env"; cargo doc --all --document-private-items

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
